export const SPECIALTIES = [
  'Obstetrics and Gynecology (OB-GYN)',
  'Psychiatry',
  'Radiology',
  'Emergency Medicine',
  'Internal Medicine',
  'Family Medicine',
  'Plastic Surgery',
  'Dermatology',
  'Urology',
  'Pathology',
  'Cardiology',
  'Pediatrics',
  'Anesthesiology',
  'Otolaryngology (ENT)',
  'Orthopedic Surgery',
  'Neurology',
  'Ophthalmology',
];
